### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Naozumi520** [matthewmcq/upscalemp3#1]
Nice project! Will pretrained model release eventually? It would be cool if it is ready out of the box. :D

**Comment by matthewmcq** [comment]
Hi! Yes it will, just working out a few kinks and then will have it up through lfs.

**Comment by matthewmcq** [comment]
Hi! The model is done! (there are some issues with noise and artifacts, but to my ears the smaller model can be a bit noisy but in general is pretty sound, and the larger model is great for super "busy" audio segments, but exhibits heavy artifacting/noise during quieter parts)

Unfortunately their sizes are too big even for LFS, so I included a markdown file with a link to download them from my Google Drive. However, if anyone knows how to get around that, I would love to just have the .keras file in the project directory.

**Comment by matthewmcq** [comment]
(sorry it took so long haha!)

**Comment by Naozumi520** [comment]
Wow, thanks! And I would suggest you upload the model to huggingface, it allows you to upload big model files! :>
